CONFIG += no_fixpath
QT = core gui sql widgets
CONFIG += no_fixpath
QT = core gui sql widgets
CONFIG += no_fixpath
QT = core gui sql widgets
CONFIG += no_fixpath
QT = core gui sql widgets
CONFIG += no_fixpath
QT = core gui sql widgets
